### ISSUE TITLE
Unable to get project info after switching document

### ISSUE THREAD

**Issue by radeeyate** [jlceda/pro-api-sdk#11]
When using this code below, you can run it a couple times before switching to a different document, trying it again, and observing it not function.
```ts
import * as extensionConfig from '../extension.json';

// eslint-disable-next-line @typescript-eslint/no-unused-vars
export function activate(status?: 'onStartupFinished', arg?: string): void { }

export function about(): void {
  try {
    const boardInfo = eda.dmt_Project.getCurrentProjectInfo();
    Promise.resolve(boardInfo).then((info) => {
      if (info) {
        eda.sys_MessageBox.showInformationMessage(eda.sys_I18n.text(JSON.stringify(info)));
      } else {
        eda.sys_MessageBox.showInformationMessage("No board info available.");
      }
    });
  } catch (error) {
    eda.sys_MessageBox.showInformationMessage(String(error))
  }
}
```

The message box for errors is not even showing up, and instead I get the following errors in the console:
```
TypeError: Cannot read properties of undefined (reading 'attrsForSearch')
    at ui.js:2965:40305
    at dt (ui.js:1095:9647)
    at getCurrentProjectInfo (ui.js:2965:40232)
(anonymous) @ api.js:4
Promise.catch (async)
t @ api.js:4
execute @ api.js:4
push @ api.js:4
(anonymous) @ api.js:4
rpcCall @ api.js:4
getCurrentProjectInfo @ api.js:4
eval @ VM334:4
(anonymous) @ api.js:7
fr @ api.js:7
(anonymous) @ api.js:30
execute @ api.js:4
publish @ api.js:4
y @ ui.js:2172
onClick @ ui.js:2172
onClick @ ui.js:1101
vYi @ ui.js:1032
EYi @ ui.js:1032
jYi @ ui.js:1032
Gpt @ ui.js:1032
Wpt @ ui.js:1032
(anonymous) @ ui.js:1032
xje @ ui.js:1035
K1t @ ui.js:1032
xEe @ ui.js:1032
cEe @ ui.js:1032
ZYi @ ui.js:1032
preload.js:17 Uncaught Error: TypeError: Cannot read properties of undefined (reading 'attrsForSearch') https://modules.lceda.cn/pro-api/0.1.79.941a04f4/api.js 4 7059 Error: TypeError: Cannot read properties of undefined (reading 'attrsForSearch')
    at api.js:4:7059
    at rr.callback (api.js:4:6500)
    at rr.execute (api.js:4:6078)
    at zo.publish (api.js:4:7378)
    at api.js:4:6744
ir @ preload.js:17
api.js:4 Uncaught Error: TypeError: Cannot read properties of undefined (reading 'attrsForSearch')
    at api.js:4:7059
    at rr.callback (api.js:4:6500)
    at rr.execute (api.js:4:6078)
    at zo.publish (api.js:4:7378)
    at api.js:4:6744
(anonymous) @ api.js:4
(anonymous) @ api.js:4
execute @ api.js:4
publish @ api.js:4
(anonymous) @ api.js:4
PromiseRejectionEvent {isTrusted: true, reason: Error: TypeError: Cannot read properties of undefined (reading 'attrsForSearch')
    at https://mod…, type: 'unhandledrejection', target: Window, currentTarget: Window, …}
api.js:4 Uncaught (in promise) Error: TypeError: Cannot read properties of undefined (reading 'attrsForSearch')
    at api.js:4:7059
    at rr.callback (api.js:4:6500)
    at rr.execute (api.js:4:6078)
    at zo.publish (api.js:4:7378)
    at api.js:4:6744
```

Edit: after digging a bit more, it seems to be a problem with the promise.

**Comment by yanranxiaoxi** [comment]
Thanks for the feedback.

After internal testing, it should be an interface parsing error due to data format modification. A bug ticket has been raised to fix it.

**Comment by yanranxiaoxi** [comment]
It has been fixed within us. The fix will be released in the next beta version (2.2.34.6).

**Comment by radeeyate** [comment]
Thanks for the quick response! Do you have any idea on when that might be released? And also - how might I be able to switch to the beta version?

**Comment by yanranxiaoxi** [comment]
I'll let you know here when the version is available.

**Comment by yanranxiaoxi** [comment]
@radeeyate Hi~

The current latest version will not be available in open beta. But you can already access it from that address:
[https://pro.easyeda.com/editor](https://pro.easyeda.com/editor?cll=debug)

**Comment by radeeyate** [comment]
Great, thank you! My extension is now reporting the expected behavior.

**Comment by radeeyate** [comment]
Hi @yanranxiaoxi,

Shortly after this banner was added this morning, the exact same error seems to be occuring even when on the new editor link.
![image](https://github.com/user-attachments/assets/39f45dae-8a93-4291-819d-b0d679d4287c)
![image](https://github.com/user-attachments/assets/de64c3e5-028a-4a85-95f1-a3ff24999a9a)

**Comment by easyeda2021** [comment]
you can download the 2.2.34.8 at https://easyeda.com/page/download

**Comment by radeeyate** [comment]
The error is still occurring on 2.2.34.8. Is the extension API not up to date for that version?

**Comment by Makerzy0226** [comment]
The issue you raised has been fixed. Please feel free to try it in the latest version (V2.2.37).

**Comment by radeeyate** [comment]
Thank you! It's working well now!
